name: storygen
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - opencv
  - transformers=4.39.3
  - huggingface_hub=0.24.6
  - accelerate=0.33.0
  - diffusers=0.26.0
  - aria2
  - git-lfs
